# Generated by Django 5.1.1 on 2024-09-19 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_PostgreSQL_searching'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
